version: '3'
services:
  prevnum-static:
    build:
      context: .
      dockerfile: Dockerfile
    image: prevnum-static-img
    container_name: prevnum-static-app
    network_mode: frontend
    ports:
      - "8091:80"
    volumes:
      - .:/usr/share/nginx/html/

networks:
  frontend:
    driver: bridge
    external: true
